config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    get :manage, on: :collection
  end
  resources :comments, only: %i(create destroy new)

  root 'posts#index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: '/'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ForestBuilder

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
                                where(:user_id => user.id).order('created_at DESC')
                              }
  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
                                        where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
                                      }

  validates :body, :presence => true
  validates :user, :presence => true


  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  #helper method to check if a comment has children
  def has_children?
    children.any?
  end


  class << self

    # Helper class method to look up a commentable object
    # given the commentable class name and id
    def find_commentable(commentable_str, commentable_id)
      commentable_str.constantize.find(commentable_id)
    end

    # Helper class method that allows you to build a comment
    # by passing a commentable object, a user_id, and comment text
    # example in readme
    def build_from(obj, user_id, comment)
      new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
    end

    def create_and_bind(params, user_id)
      commentable = Comment.find_commentable params[:commentable_type], params[:commentable_id]
      comment = Comment.build_from commentable, user_id, params[:body]
      comment.save!
      comment.move_to_child_of Comment.find(params[:parent_id]) if params[:parent_id].present?
      comment
    end

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource only: :destroy

  def new
    authorize! :create, Comment
    @comment = Comment.new params.permit(:commentable_id, :commentable_type, :parent_id)
  end

  def create
    authorize! :create, Comment
    @comment = Comment.create_and_bind params.require(:comment), current_user.id
  rescue Exception => e
    render_alert e
  end

  def destroy
    @comment.destroy!
  rescue Exception => e
    render_alert e
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.slim
.comment id = "comment-#{comment.id}"
  .pull-left.comment-avatar
    = image_tag comment.user.avatar.url(:thumb), class: 'img-thumbnail'
  .panel.panel-default.comment-container
    .panel-heading

      => link_to '', comment_path(comment), :method => :delete, :remote => true, :confirm => 'Are you sure', \
        :class => 'glyphicon glyphicon-remove pull-right', id: "remove-comment-#{comment.id}"  if can? :destroy, comment
      h4.panel-title
        => comment.user.decorate.name
        small= l comment.updated_at
    .panel-body
      p= comment.body
    .panel-footer id="comment-footer-#{comment.id}"
      .text-right
        = link_to '', new_comment_path(commentable_id: comment.commentable_id, commentable_type: comment.commentable_type, parent_id: comment.id ),
                  remote: true, class: 'glyphicon glyphicon-comment', id: "add-comment-form-for-comment-#{comment}"  if can? :create, Comment
  = render partial: 'comments/comment', collection: comment.children

app/views/comments/_form.slim
.comment-form id= "comment-form-for-parent-#{comment.parent_id}"
  = simple_form_for comment, :remote => true do |f|
    = f.input :body, :input_html => { :rows => 2, class: 'form-control' }, :label => false
    - %w(commentable_id commentable_type parent_id).each do |attr|
      = f.input attr, :as => :hidden, :value => comment.send(attr)
    br
    .text-right
      = f.button :submit, :class => 'btn btn-sm btn-primary'

app/views/comments/create.js.erb
(function() {
    $('#comment-form-for-parent-<%= @comment.parent_id %>').remove()
    $('#comment-<%= @comment.parent_id %> > .comment-container').after('<%= j render partial: 'comment', object: @comment %>').next().hide(0).show(400)
})()

app/views/comments/destroy.js.erb
(function() {
    $('#comment-<%= params[:id] %>').hide(400)
})()

app/views/comments/new.js.erb
(function() {
    $('#comment-footer-<%= params[:parent_id] %>').append('<%= j render partial: 'form', object: @comment, as: :comment %>')
})()