config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    get :manage, on: :collection
  end
  resources :comments, only: %i(create destroy new)

  root 'posts#index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: '/'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :published_at, :title, :content

  scope :published, -> { where 'posts.published_at < current_timestamp' }

  acts_as_commentable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.published.order(published_at: :desc).paginate(:page => params[:page], per_page: 10)
  end

  def manage
    @posts = current_user.posts.order(created_at: :desc).paginate(:page => params[:page], per_page: 20)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comment_threads.includes(:user).order(created_at: :desc).build_forest
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :published_at, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= simple_form_for @post, :html => { :class => "form-horizontal" }, turboboost: true do |f|
  = f.input :title, input_html: {class: 'form-control'}
  = error_span(@post[:title])
  = f.input :content, as: :ckeditor
  = error_span(@post[:content])
  = f.input :published_at
  = error_span(@post[:published_at])
  = f.button :submit, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn btn-default'

app/views/posts/edit.html.slim
- model_class = Post
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/index.html.slim
- model_class = Post
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
= will_paginate @posts, renderer: BootstrapPagination::Rails
- @posts.each do |post|
  h4= link_to post.title, post_path(post)
  = post.user.decorate.name
  .pull-right= l post.published_at

app/views/posts/manage.html.slim
- model_class = Post
div class="page-header"
  h1 Manage #{t '.title', :default => model_class.model_name.human.pluralize.titleize}
= will_paginate @posts, renderer: BootstrapPagination::Rails
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:published_at)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @posts.each do |post|
      tr
        td= link_to post.id, post_path(post)
        td= post.title
        td= post.published_at
        td= l post.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(post), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-primary'

app/views/posts/new.html.slim
- model_class = Post
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/show.html.slim
- model_class = Post
div class="page-header"
  h1= @post.title
= @post.content.html_safe
hr
.pull-right= l @post.published_at
.pull-left= @post.user.decorate.name
.clearfix
hr
.comments
  #comment-
    .comment-container
      #comment-footer-
        .text-right
          = link_to 'Добавить комментарий', new_comment_path(commentable_id: @post.id, commentable_type: 'Post'),
                    remote: true, id: 'add-comment-form-for-comment-' if can? :create, Comment
  = render partial: 'comments/comment', collection: @comments
hr
= link_to t('.back', :default => t("helpers.links.back")), posts_path, :class => 'btn btn-default'
-if can? :manage, @post
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post), :class => 'btn btn-default'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
br
br