config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    get :manage, on: :collection
  end
  resources :comments, only: %i(create destroy new)

  root 'posts#index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: '/'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "SimpleBlog"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to 'SimpleBlog', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          .nav.pull-right
            - if user_signed_in?
              => link_to current_user.decorate.name, edit_user_registration_path, class: 'btn navbar-btn'
              = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn'
            - else
              => link_to 'Sign in', new_user_session_path, class: 'btn btn-primary navbar-btn'
              = link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn'

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to 'Posts', posts_path
              li= link_to 'Manage Posts', manage_posts_path if can? :manage, Post

    footer.footer
      .container.text-muted.text-center
          br
          p &copy; Company 2015